### ISSUE TITLE
Header for compressed data files.

### ISSUE THREAD

**Issue by wepl** [askeksa/Shrinkler#3]
When compressing files in --data mode the compressed file has no header.
It would be useful to have the possibility to add a small header, e.g. 4-byte ID + uncompressed size + compressed size.

**Comment by wepl** [comment]
The header should also contain the 'safety margin' for decompression. This could maybe stored in the high byte of the compressed size.

**Comment by askeksa** [comment]
Thanks for the suggestion.

I've been a bit wary of defining a format, since I don't really see Crinkler as an interchange format. But I do see the benefit of having a standard format anyway, especially to make it easier to load compressed files.

So I have given the format a bit of thought. Since it can be difficult to foresee all use cases up front, I want it to be extensible. It could be something like:
```
LONG id; // $53687269 ('Shri')
BYTE majorVersion;
BYTE minorVersion;
WORD headerSize; // Number of bytes following this before the data
LONG compressedSize;
LONG uncompressedSize;
LONG safetyMargin; // In theory, this can be arbitrarily big
LONG flags; // Only one flag defined: bit 0 = parity context
```
Any further header bytes will be ignored. Thus, in the absence of breaking changes, newer files can still be decompressed by older decompressors.

WDYT?

**Comment by wepl** [comment]
This looks fine to me.
Would be great to have this added.

**Comment by askeksa** [comment]
Implemented in https://github.com/askeksa/Shrinkler/commit/04d3b52d0f2042b41114eb542176fd0a4e1f2a61.

Also added, in https://github.com/askeksa/Shrinkler/commit/6df7e8bae25a62ef24b2b58856c2f07422c43d36, some utility code to load a Shrinkler-compressed data file with header, handling allocation, appropriate overlap and decompression.
